//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  // Version
        ///  &quot;version&quot;: &quot;20180322.1&quot;,
        ///
        ///  // Duty
        ///  &quot;instances&quot;: {
        ///    // 2.0 A Realm Reborn
        ///    // 2.0 Dungeons
        ///    &quot;4&quot;: {
        ///      &quot;name&quot;: &quot;天然要害沙斯塔夏溶洞（15级）&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;8&quot;: {
        ///      &quot;name&quot;: &quot;休养胜地布雷福洛克斯野营地（32级）&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;10&quot;: {
        ///      &quot;name&quot;: &quot;神灵圣域放浪神古神殿（50级）&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;3&quot;: {
        ///      &quot;name&quot;: &quot;封锁坑道铜铃铜山（17级）&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Data_EN_US {
            get {
                return ResourceManager.GetString("Data_EN_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  // 버전
        ///  &quot;version&quot;: &quot;20170905.1&quot;,
        ///
        ///  // 임무
        ///  &quot;instances&quot;: {
        ///    // 2.0 신생 에오르제아
        ///    // 2.0 던전
        ///    &quot;157&quot;: {
        ///      &quot;name&quot;: &quot;사스타샤 침식 동굴&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;158&quot;: {
        ///      &quot;name&quot;: &quot;브레이플록스의 야영지&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;159&quot;: {
        ///      &quot;name&quot;: &quot;방랑자의 궁전&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///    &quot;161&quot;: {
        ///      &quot;name&quot;: &quot;구리종 광산&quot;,
        ///      &quot;tank&quot;: &quot;1&quot;,
        ///      &quot;healer&quot;: &quot;1&quot;,
        ///      &quot;dps&quot;: &quot;2&quot;
        ///    },
        ///  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Data_KO_KR {
            get {
                return ResourceManager.GetString("Data_KO_KR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;app-name&quot;: &quot;Duty/FATE Assist&quot;,
        ///
        ///
        ///  &quot;unknown-instance&quot;: &quot;Unknown Duty ({0})&quot;,
        ///  &quot;unknown-roulette&quot;: &quot;Unknown Roulette ({0})&quot;,
        ///  &quot;unknown-area&quot;: &quot;Unknown Area ({0})&quot;,
        ///  &quot;unknown-fate&quot;: &quot;Unknown FATE ({0})&quot;,
        ///
        ///
        ///  &quot;notification-app-updated&quot;: &quot;Version {0} Updated&quot;,
        ///  &quot;notification-queue-matched&quot;: &quot;&lt; {0} &gt; 匹配完成!&quot;,
        ///
        ///
        ///  &quot;tweet-fate-occured&quot;: &quot;&lt; {0} &gt; 临危受命出现!&quot;,
        ///  &quot;tweet-queue-matched&quot;: &quot;&lt; {0} &gt; 匹配完成!&quot;,
        ///
        ///
        ///  &quot;fate-preset-animus-SkyfireI&quot;: &quot;炎天一卷&quot;,
        ///  &quot;fate-preset-animus-SkyfireII&quot;: &quot;炎天二卷&quot;,
        ///  &quot;fate-preset-animus-Neth [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Localization_EN_US {
            get {
                return ResourceManager.GetString("Localization_EN_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;app-name&quot;: &quot;임무/돌발 찾기 도우미&quot;,
        ///
        ///
        ///  &quot;unknown-instance&quot;: &quot;알 수 없는 임무 ({0})&quot;,
        ///  &quot;unknown-roulette&quot;: &quot;알 수 없는 무작위 임무 ({0})&quot;,
        ///  &quot;unknown-area&quot;: &quot;알 수 없는 지역 ({0})&quot;,
        ///  &quot;unknown-fate&quot;: &quot;알 수 없는 돌발 ({0})&quot;,
        ///
        ///
        ///  &quot;notification-app-updated&quot;: &quot;버전 {0} 업데이트됨&quot;,
        ///  &quot;notification-queue-matched&quot;: &quot;&lt; {0} &gt; 매칭!&quot;,
        ///
        ///
        ///  &quot;tweet-fate-occured&quot;: &quot;&lt; {0} &gt; 돌발 발생!&quot;,
        ///  &quot;tweet-queue-matched&quot;: &quot;&lt; {0} &gt; 매칭!&quot;,
        ///
        ///
        ///  &quot;fate-preset-animus-SkyfireI&quot;: &quot;불의 서 1권&quot;,
        ///  &quot;fate-preset-animus-SkyfireII&quot;: &quot;불의 서 2권&quot;,
        ///  &quot;fate-preset-animus-NetherfireI&quot;: &quot;불의 서 3권&quot;,
        ///  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Localization_KO_KR {
            get {
                return ResourceManager.GetString("Localization_KO_KR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream remind {
            get {
                return ResourceManager.GetStream("remind", resourceCulture);
            }
        }
    }
}
